//
// API ENDPOINTS USER
//

// HÄMTA ALLA USERS // SKICKA INTE MED LÖSENORD // BARA ID, NAMN + EMAIL PÅ ALLA USERS
# @name getUsers
GET http://localhost:3000/api/users

###

// HÄMTA SPECIFIK USER // SKICKA HELA OBJEKTET
POST http://localhost:3000/api/users/
Content-Type: application/json

{
  "id": "64185293fb32b0859d142c33"
}

###

// SKAPA USER
POST http://localhost:3000/api/users/add
Content-Type: application/json

{
  "name": "Testaa Testsson",
  "email": "testaa@mail.com",
  "password": "test"
}

###

// LOGGA IN USER
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "hejsan@mail.com",
  "password": "test123"
}

###

//
// API ENDPOINTS PRODUKTER
//

// HÄMTA ALLA PRODUKTER

# @name getProducts
GET http://localhost:3000/api/products

###

// HÄMTA SPECIFIK PRODUKT
GET http://localhost:3000/api/products/64198cd5135a6d4ba7834d6e

###

// SKAPA PRODUKT
POST http://localhost:3000/api/products/add
Content-Type: application/json

{
  "name": "Produkt 2",
  "description": "Beskrivning av produkt 2",
  "price": 200, 
  "stock": 20
}

###

//
// API ENDPOINTS ORDERS
//

// SKAPA ORDER FÖR EN SPECIFIK USER // PRODUCTS ÄR EN ARRAY MOTSVARANDE INNEHÅLLET I KUNDVAGN
POST http://localhost:3000/api/orders/add
Content-Type: application/json

{
  "user": "{{getUsers.response.body.$[0].id}}",
      "products": [
    {
      "productId": "// ID PÅ EN PRODUKT",
      "quantity": 1
    },
    {
      "productId": "// ID PÅ EN PRODUKT",
      "quantity": 2
    }
  ]
}

###


// HÄMTA ALLA ORDERS
GET http://localhost:3000/api/orders/all/

###